---
image: jdubz/ci-docker-ansible:latest

services:
  - docker:19.03.1-dind

variables:
  BASH_ENV: /root/.bashrc

.molecule:
  stage: test
  cache:
    paths:
      - .tox
  before_script:
    - pyenv local 2.7.18 3.6.11 3.7.7 3.8.3
    - pip3 install tox
  script:
    - tox

debian9:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-stretch
    MOLECULE_IMAGE: debian:stretch-slim

debian10:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-buster
    MOLECULE_IMAGE: debian:buster-slim

ubuntu1604:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-xenial
    MOLECULE_IMAGE: ubuntu:xenial

ubuntu1804:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-bionic
    MOLECULE_IMAGE: ubuntu:bionic
